services:
  genai-postgres:
    container_name: genai_postgres_container
    image: postgres:15
    environment:
      - 'POSTGRES_DB=genaidb'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=jeral'
    ports:
      - "5440:5432"
